--Read the dataset
Select * from PortfolioProject.[dbo].[Companies_US];

--Most prevailing Industry
Select Industry,count(*) as Total_Companies
from PortfolioProject.[dbo].[Companies_US]
Group by Industry
Order by Total_Companies desc;

--Top 25 Companies with Increase in Revenue growth


SELECT Top 25 Rank, Name, REPLACE(Revenue_growth, '%', '') AS Revenue_growth
FROM PortfolioProject.[dbo].[Companies_US]
ORDER BY CAST(REPLACE(Revenue_growth, '%', '') AS DECIMAL(5,2)) DESC;


-- Top 10 Companies with highest employee count

select Top 10 Name,Industry,Employees
FROM PortfolioProject.[dbo].[Companies_US]
Order by Employees desc;

--Total Revenue Generated by top 100 US companies

select sum(Revenue_USD_millions) as Total_Revenue
FROM PortfolioProject.[dbo].[Companies_US];



--Break Headquarters into city and state

select Headquarters,
Left(Headquarters,Charindex(',', Headquarters) -1) as City,
Right(Headquarters,Len(Headquarters)-charindex(',',Headquarters)) as State
FROM PortfolioProject.[dbo].[Companies_US];

--Add City & State to the table

Alter Table PortfolioProject.[dbo].[Companies_US]
Add City nvarchar(50), State nvarchar(50);

Update PortfolioProject.[dbo].[Companies_US]
set City = Left(Headquarters,Charindex(',', Headquarters) -1),
State = Right(Headquarters,Len(Headquarters)-charindex(',',Headquarters));

Select * from PortfolioProject.[dbo].[Companies_US];

--Drop Headquartes from the table

Alter Table PortfolioProject.[dbo].[Companies_US]
Drop column Headquarters;

--Industry analysis 

SELECT 
    Industry,
    SUM(Revenue_USD_millions) AS Total_revenue,
    CAST(ROUND(AVG(CAST(REPLACE(Revenue_growth, '%', '') AS DECIMAL(5, 2))), 2) AS DECIMAL(5, 2)) AS Avg_revenue_growth,
    SUM(Employees) AS Total_employees
FROM 
    PortfolioProject.[dbo].[Companies_US]
GROUP BY 
    Industry
ORDER BY
    Total_revenue DESC,
	Total_employees;

--Top 10 Revenue

select Top 10 
    Name,
    Industry,
    Revenue_USD_millions,
	Replace(Revenue_growth,'%','') as Revenue_growth,
	Employees
From PortfolioProject.[dbo].[Companies_US]
Order by Revenue_USD_millions Desc;

--Top 10 Revenue Growth

select Top 10 
    Name,
    Industry,
    Revenue_USD_millions,
	Replace(Revenue_growth,'%','') as Revenue_growth,
	Employees
From PortfolioProject.[dbo].[Companies_US]
Order by cast(Replace(Revenue_growth,'%','') as decimal(5,2)) Desc;

--Top 10 Employees
select Top 10 
    Name,
    Industry,
    Revenue_USD_millions,
	Replace(Revenue_growth,'%','') as Revenue_growth,
	Employees
From PortfolioProject.[dbo].[Companies_US]
Order by Employees Desc;

--Top performing Industries by revenue

Select Industry, sum(Revenue_USD_millions) as Total_revenue
FROM PortfolioProject.[dbo].[Companies_US]
Group by Industry 
Order by Total_revenue desc;

--Top performing Industries by average Revenue growth

Select Industry,
       Avg(cast(replace(Revenue_growth,'%','') as decimal(5,2))) as Avg_revenue_growth
FROM PortfolioProject.[dbo].[Companies_US]
Group by Industry 
Order by Avg_revenue_growth Desc;

--Top 10 Companies by revenue

SELECT TOP 10
    Name,
    Industry,
    Revenue_USD_millions
FROM 
    PortfolioProject.[dbo].[Companies_US]
ORDER BY 
    Revenue_USD_millions DESC;

--Top 10 Companies with highest revenue growth

Select Top 10 Name, 
              Industry, 
			  Revenue_growth
FROM PortfolioProject.[dbo].[Companies_US]
Order by CAST(Replace(Revenue_growth,'%','') as decimal(5,2)) Desc;




--Distribution of company headquarters by city,state

select City,
       State,
	   count(*) as num_of_companies
From PortfolioProject.[dbo].[Companies_US]
Group by City, State
Order by num_of_companies Desc;

--Top 10 States by Revenue

Select Top 10 State,Revenue_USD_millions
From PortfolioProject.[dbo].[Companies_US]
Order by Revenue_USD_millions Desc;

--Top 10 States by employees 

Select Top 10 State,Employees
From PortfolioProject.[dbo].[Companies_US]
Order by Employees Desc;

--Top 10 State by revenue growth

Select Top 10 State,Revenue_growth
FROM PortfolioProject.[dbo].[Companies_US]
Order by CAST(Replace(Revenue_growth,'%','') as decimal(5,2)) Desc;

--Companies in New York

Select Name,Industry,Revenue_USD_millions,City
FROM PortfolioProject.[dbo].[Companies_US]
Where City = 'New York City';


Select Name,Industry,Revenue_USD_millions,City,State
FROM PortfolioProject.[dbo].[Companies_US]
Where State = ' New York';

select * FROM PortfolioProject.[dbo].[Companies_US]

--Companies in Washington
Select Name,Industry,Revenue_USD_millions,City,State
FROM PortfolioProject.[dbo].[Companies_US]
Where State = ' Washington';

--Companies in Texas
Select Name,Industry,Revenue_USD_millions,City,State
FROM PortfolioProject.[dbo].[Companies_US]
Where State = ' Texas';


--Companies in California

Select Name,Industry,Revenue_USD_millions,City,State
FROM PortfolioProject.[dbo].[Companies_US]
Where State = ' California';
--Top 15 Cities by Companies


SELECT 
    Top 15 City,
    COUNT(*) AS Number_of_Companies
FROM 
    PortfolioProject.[dbo].[Companies_US]
GROUP BY 
    City
ORDER BY 
    Number_of_Companies DESC;

--Top 15 States by companies

SELECT 
    Top 15 State,
    COUNT(*) AS Number_of_Companies
FROM 
    PortfolioProject.[dbo].[Companies_US]
GROUP BY 
    State
ORDER BY 
    Number_of_Companies DESC;

--Inustries in Each state

SELECT 
    State,
    Industry,
    COUNT(*) AS Num_Companies
FROM 
    PortfolioProject.[dbo].[Companies_US]
GROUP BY 
    State, Industry
ORDER BY 
    State, Num_Companies DESC;



